# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "2.7"
  - "pypy"

cache:
  directories:
  - $HOME/iverilog
      
# get some stuff to install
before_install:
  - chmod +x ./scripts/ci/install_iverilog.sh
  - ./scripts/ci/install_iverilog.sh

# command to install dependencies
install:
  - pwd
  - chmod +x ./scripts/ci/install_myhdl.sh
  - ./scripts/ci/install_myhdl.sh
  - pip install coverage
  - pip install coveralls
  - pip install Pillow

# run the test, nosetests can be used
script:
   - cd test
   - python test_jpegenc.py

notifications:
  email: false
