# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - gperf
      
cache:
  directories:
  - $HOME/iverilog
      
# get some stuff to install
before_install:
  - export PATH=$PATH:$HOME/iverilog/bin/
  - chmod +x ./scripts/ci/install_iverilog.sh
  - ./scripts/ci/install_iverilog.sh

# command to install dependencies
install:
  - pwd
  - chmod +x ./scripts/ci/install_myhdl.sh
  - ./scripts/ci/install_myhdl.sh
  - pip install coverage
  - pip install coveralls
  - pip install Pillow
  - pip install .


script:
   - cd test
   - coverage run --source jpegenc -m py.test -s
   - cp .coverage ../

after_success:
   - coveralls

notifications:
  email: true
